2024-08-18 20:31:07,201 INFO    StreamThr :3101596 [internal.py:wandb_internal():85] W&B internal server running at pid: 3101596, started at: 2024-08-18 20:31:07.200317
2024-08-18 20:31:07,204 DEBUG   HandlerThread:3101596 [handler.py:handle_request():158] handle_request: status
2024-08-18 20:31:07,207 INFO    WriterThread:3101596 [datastore.py:open_for_write():87] open: /cluster/home/pgoyal/main/test/wandb/run-20240818_203107-0bmgljxc/run-0bmgljxc.wandb
2024-08-18 20:31:07,208 DEBUG   SenderThread:3101596 [sender.py:send():379] send: header
2024-08-18 20:31:07,210 DEBUG   SenderThread:3101596 [sender.py:send():379] send: run
2024-08-18 20:31:07,667 INFO    SenderThread:3101596 [dir_watcher.py:__init__():211] watching files in: /cluster/home/pgoyal/main/test/wandb/run-20240818_203107-0bmgljxc/files
2024-08-18 20:31:07,667 INFO    SenderThread:3101596 [sender.py:_start_run_threads():1188] run started: 0bmgljxc with start time 1724005867.201247
2024-08-18 20:31:07,678 DEBUG   HandlerThread:3101596 [handler.py:handle_request():158] handle_request: check_version
2024-08-18 20:31:07,678 DEBUG   SenderThread:3101596 [sender.py:send_request():406] send_request: check_version
2024-08-18 20:31:07,995 DEBUG   HandlerThread:3101596 [handler.py:handle_request():158] handle_request: run_start
2024-08-18 20:31:08,023 DEBUG   HandlerThread:3101596 [system_info.py:__init__():26] System info init
2024-08-18 20:31:08,023 DEBUG   HandlerThread:3101596 [system_info.py:__init__():41] System info init done
2024-08-18 20:31:08,023 INFO    HandlerThread:3101596 [system_monitor.py:start():194] Starting system monitor
2024-08-18 20:31:08,023 INFO    SystemMonitor:3101596 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-18 20:31:08,023 INFO    HandlerThread:3101596 [system_monitor.py:probe():214] Collecting system info
2024-08-18 20:31:08,029 INFO    SystemMonitor:3101596 [interfaces.py:start():188] Started cpu monitoring
2024-08-18 20:31:08,029 INFO    SystemMonitor:3101596 [interfaces.py:start():188] Started disk monitoring
2024-08-18 20:31:08,030 INFO    SystemMonitor:3101596 [interfaces.py:start():188] Started gpu monitoring
2024-08-18 20:31:08,031 INFO    SystemMonitor:3101596 [interfaces.py:start():188] Started memory monitoring
2024-08-18 20:31:08,031 INFO    SystemMonitor:3101596 [interfaces.py:start():188] Started network monitoring
2024-08-18 20:31:08,069 DEBUG   HandlerThread:3101596 [system_info.py:probe():152] Probing system
2024-08-18 20:31:08,072 DEBUG   HandlerThread:3101596 [gitlib.py:_init_repo():56] git repository is invalid
2024-08-18 20:31:08,072 DEBUG   HandlerThread:3101596 [system_info.py:probe():200] Probing system done
2024-08-18 20:31:08,072 DEBUG   HandlerThread:3101596 [system_monitor.py:probe():223] {'os': 'Linux-5.15.0-102-generic-x86_64-with-glibc2.35', 'python': '3.11.6', 'heartbeatAt': '2024-08-18T18:31:08.069137', 'startedAt': '2024-08-18T18:31:07.189174', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'host': 'eu-g6-025', 'username': 'pgoyal', 'executable': '/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/bin/python', 'cpu_count': 128, 'cpu_count_logical': 128, 'cpu_freq': {'current': 1611.6399609375, 'min': 1500.0, 'max': 3100.0}, 'cpu_freq_per_core': [{'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 2300.0, 'min': 1500.0, 'max': 3100.0}, {'current': 2708.275, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 3100.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 3750.052, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 3750.058, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 3100.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 2586.038, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 3750.052, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}, {'current': 1500.0, 'min': 1500.0, 'max': 3100.0}], 'disk': {'/': {'total': 10.0, 'used': 6.059978485107422}}, 'gpu': 'NVIDIA GeForce RTX 4090', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4090', 'memory_total': 25757220864}], 'memory': {'total': 375.3251152038574}}
2024-08-18 20:31:08,072 INFO    HandlerThread:3101596 [system_monitor.py:probe():224] Finished collecting system info
2024-08-18 20:31:08,072 INFO    HandlerThread:3101596 [system_monitor.py:probe():227] Publishing system info
2024-08-18 20:31:08,075 INFO    HandlerThread:3101596 [system_monitor.py:probe():229] Finished publishing system info
2024-08-18 20:31:08,669 INFO    Thread-12 :3101596 [dir_watcher.py:_on_file_created():271] file/dir created: /cluster/home/pgoyal/main/test/wandb/run-20240818_203107-0bmgljxc/files/wandb-metadata.json
2024-08-18 20:32:08,031 DEBUG   SystemMonitor:3101596 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-18 20:34:28,080 INFO    memory    :3101596 [interfaces.py:monitor():138] Process proc.memory.rssMB has exited.
2024-08-18 20:34:28,081 DEBUG   SystemMonitor:3101596 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-08-18 20:34:28,083 DEBUG   SystemMonitor:3101596 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-08-18 20:34:28,226 WARNING StreamThr :3101596 [internal.py:is_dead():413] Internal process exiting, parent pid 3100845 disappeared
2024-08-18 20:34:28,226 ERROR   StreamThr :3101596 [internal.py:wandb_internal():151] Internal process shutdown.
2024-08-18 20:34:28,698 INFO    WriterThread:3101596 [datastore.py:close():296] close: /cluster/home/pgoyal/main/test/wandb/run-20240818_203107-0bmgljxc/run-0bmgljxc.wandb
2024-08-18 20:34:28,828 INFO    SenderThread:3101596 [sender.py:finish():1608] shutting down sender
2024-08-18 20:34:28,828 INFO    SenderThread:3101596 [dir_watcher.py:finish():358] shutting down directory watcher
2024-08-18 20:34:29,694 INFO    SenderThread:3101596 [dir_watcher.py:finish():388] scan: /cluster/home/pgoyal/main/test/wandb/run-20240818_203107-0bmgljxc/files
2024-08-18 20:34:29,694 INFO    SenderThread:3101596 [dir_watcher.py:finish():402] scan save: /cluster/home/pgoyal/main/test/wandb/run-20240818_203107-0bmgljxc/files/config.yaml config.yaml
2024-08-18 20:34:29,694 INFO    SenderThread:3101596 [dir_watcher.py:finish():402] scan save: /cluster/home/pgoyal/main/test/wandb/run-20240818_203107-0bmgljxc/files/wandb-metadata.json wandb-metadata.json
2024-08-18 20:34:29,697 INFO    SenderThread:3101596 [file_pusher.py:finish():169] shutting down file pusher
2024-08-18 20:34:29,697 INFO    SenderThread:3101596 [file_pusher.py:join():175] waiting for file pusher
2024-08-18 20:34:29,942 ERROR   wandb-upload_0:3101596 [internal_api.py:execute():344] 404 response executing GraphQL.
2024-08-18 20:34:29,943 ERROR   wandb-upload_0:3101596 [internal_api.py:execute():345] {"errors":[{"message":"run gemma-sft-lora-socratic/0bmgljxc not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-08-18 20:34:29,943 ERROR   Thread-11 (_thread_body):3101596 [step_upload.py:_handle_event():144] Failed to upload file: /cluster/home/pgoyal/main/test/wandb/run-20240818_203107-0bmgljxc/files/config.yaml
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2464, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 347, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2464, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 347, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
wandb.errors.CommError: [Errno 32] Broken pipe
2024-08-18 20:34:29,962 ERROR   wandb-upload_1:3101596 [internal_api.py:execute():344] 404 response executing GraphQL.
2024-08-18 20:34:29,962 ERROR   wandb-upload_1:3101596 [internal_api.py:execute():345] {"errors":[{"message":"run gemma-sft-lora-socratic/0bmgljxc not found during createRunFiles","path":["createRunFiles"]}],"data":{"createRunFiles":null}}
2024-08-18 20:34:29,962 ERROR   Thread-11 (_thread_body):3101596 [step_upload.py:_handle_event():144] Failed to upload file: /cluster/home/pgoyal/main/test/wandb/run-20240818_203107-0bmgljxc/files/wandb-metadata.json
Traceback (most recent call last):
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2464, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 347, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 223, in run_and_notify
    self._do_upload(event)
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/filesync/step_upload.py", line 243, in _do_upload
    job.run()
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 56, in run
    self.push()
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/filesync/upload_job.py", line 105, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2464, in upload_urls
    query_result = self.gql(
                   ^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 347, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/errors/term.py", line 64, in termerror
    _log(
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/wandb/errors/term.py", line 103, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/cluster/software/stacks/2024-05/spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-13.2.0/python-3.11.6-m4n2ny4dwaqmeobuqquo3gpyw2bct67i/lib/python3.11/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
wandb.errors.CommError: [Errno 32] Broken pipe
2024-08-18 20:34:30,197 INFO    SenderThread:3101596 [file_stream.py:finish():601] file stream finish called
2024-08-18 20:34:30,328 INFO    SenderThread:3101596 [file_stream.py:finish():605] file stream finish is done
